version: 0.2
phases:
  pre_build:
    commands:
     - New-Item -ItemType Junction -Path C:\Src1 -Value $Env:CODEBUILD_SRC_DIR
     - cd C:\Src1  
  build:
    commands:
     - nuget restore
     - msbuild
artifacts:
  files:
    - 'ConsoleApp/bin/Debug/*'
    - 'appspec.yml'
    - 'app-stop.cmd'
    - 'app-start.cmd'
